/* Shared site header behaviour — theme toggle + language switcher (i18n). */
// Theme toggle: cycles dark → light (default: dark). Remembers the choice.
  (function () {
    var root = document.documentElement
    var THEMES = ['dark', 'light']
    function apply(t) {
      if (t === 'dark') root.removeAttribute('data-theme')
      else root.setAttribute('data-theme', t)
      try { localStorage.setItem('pg-theme', t) } catch (e) {}
    }
    var saved = localStorage.getItem('pg-theme')
    apply(THEMES.indexOf(saved) >= 0 ? saved : 'dark')
    var btn = document.getElementById('themeToggle')
    if (btn) btn.addEventListener('click', function () {
      var i = THEMES.indexOf(localStorage.getItem('pg-theme'))
      apply(THEMES[(i + 1) % THEMES.length] || 'light')
    })
  })()

  // ===== Language switcher (i18n) =====
  // English lives in the markup; this dictionary overrides per language. Any key not translated for a
  // language simply falls back to the English source, so nothing ever breaks or goes blank.
  ;(function () {
    var LANGS = [
      ['en','🇺🇸','English'],['ru','🇷🇺','Русский'],['de','🇩🇪','Deutsch'],['es','🇪🇸','Español'],
      ['fr','🇫🇷','Français'],['hi','🇮🇳','हिन्दी'],['pt','🇧🇷','Português'],['ja','🇯🇵','日本語'],
      ['it','🇮🇹','Italiano'],['pl','🇵🇱','Polski'],['tr','🇹🇷','Türkçe'],['ko','🇰🇷','한국어'],
      ['nl','🇳🇱','Nederlands'],['zh','🇨🇳','简体中文'],['ar','🇸🇦','العربية']
    ]
    var T = {
      ru:{nav_how:"Как это работает",nav_features:"Возможности",nav_videos:"Видео",nav_pricing:"Цены",nav_faq:"Вопросы",nav_add:"Добавить в Chrome",hero_eyebrow:"Расширение Chrome · 100% в вашем браузере",hero_h1:"Сохраняйте доски Pinterest <span class='red'>быстро</span>.",hero_lead:"Отмечайте нужные пины прямо на странице и скачивайте их в ZIP, папку или PDF. Без вставки ссылок. Без загрузок на сервер. Без ожидания.",hero_cta1:"Добавить в Chrome — бесплатно",hero_cta2:"▶ Смотреть демо 30 сек",trust1:"<b>HD</b> фото и видео",trust2:"<b>Приватные доски</b> поддерживаются",trust3:"<b>Без аккаунта</b> и серверов",strip1_t:"Быстро",strip1_s:"Вся доска в один клик",strip2_t:"Просто",strip2_s:"Выбор пинов на странице",strip3_t:"Приватно",strip3_s:"Работает локально, без загрузок",strip4_t:"Бесплатный старт",strip4_s:"Установка за секунды",price_eyebrow:"Цены",price_h2:"Выберите, на сколько вам нужно.",price_lead:"Начните бесплатно. Откройте <b>всё</b> от $3.99 — на платных тарифах без ограничений.",plan_free:"Бесплатно",plan_24h:"24 часа",plan_2w:"2 недели",plan_1m:"1 месяц",plan_1y:"1 год",tag_onetime:"Разово",tag_popular:"Популярно",tag_best:"Выгодно",per_free:"Без карты · старт сразу",per_24h:"Без подписки · таймер с момента покупки",per_2w:"Продление каждые 2 недели · отмена в любой момент",per_1m:"Оплата помесячно · отмена в любой момент",per_1y:"≈ $6.58 / мес · оплата за год · экономия ~34%",free_saves:"20 сохранений пинов / месяц",free_boards:"2 скачивания досок / месяц",feat_hd:"HD-качество",feat_photos:"Фото и видео",feat_pins:"<b>Безлимит</b> пинов и досок",feat_profile:"Весь профиль и разделы",feat_zip:"ZIP, папки и PDF",feat_video:"Видео (MP4) и очередь загрузок",btn_free:"Добавить в Chrome",btn_24h:"Купить день",btn_2w:"Купить 2 недели",btn_1m:"Купить месяц",btn_1y:"Купить год",foot_note:"24-часовой доступ — <b>разовая</b> покупка (без продления). Тарифы на 2 недели / месяц / год продлеваются автоматически — <b>отмена в любой момент</b>. Цены в USD."},
      de:{nav_how:"So funktioniert's",nav_features:"Funktionen",nav_videos:"Videos",nav_pricing:"Preise",nav_faq:"FAQ",nav_add:"Zu Chrome hinzufügen",hero_eyebrow:"Chrome-Erweiterung · 100% in deinem Browser",hero_h1:"Pinterest-Pinnwände <span class='red'>blitzschnell</span> speichern.",hero_lead:"Markiere die gewünschten Pins direkt auf der Seite und lade sie als ZIP, Ordner oder PDF. Kein Link-Einfügen. Keine Uploads. Kein Warten.",hero_cta1:"Zu Chrome hinzufügen — kostenlos",hero_cta2:"▶ 30-Sek-Demo ansehen",trust1:"<b>HD</b>-Bilder & -Videos",trust2:"<b>Private Pinnwände</b> unterstützt",trust3:"<b>Kein Konto</b>, keine Server",strip1_t:"Schnell",strip1_s:"Ganze Pinnwand mit einem Klick",strip2_t:"Einfach",strip2_s:"Pins direkt auf der Seite wählen",strip3_t:"Privat",strip3_s:"Läuft lokal, keine Uploads",strip4_t:"Gratis starten",strip4_s:"In Sekunden installiert",price_eyebrow:"Preise",price_h2:"Wähle, wie lange du es brauchst.",price_lead:"Gratis starten. <b>Alles</b> ab $3.99 freischalten — keine Funktionssperren bei bezahlten Plänen.",plan_free:"Gratis",plan_24h:"24 Stunden",plan_2w:"2 Wochen",plan_1m:"1 Monat",plan_1y:"1 Jahr",tag_onetime:"Einmalig",tag_popular:"Beliebt",tag_best:"Bester Wert",per_free:"Keine Karte · sofort starten",per_24h:"Kein Abo · Timer startet beim Kauf",per_2w:"Verlängert sich alle 2 Wochen · jederzeit kündbar",per_1m:"Monatliche Zahlung · jederzeit kündbar",per_1y:"≈ $6.58 / Mon · jährlich · ~34% sparen",free_saves:"20 Pin-Speicherungen / Monat",free_boards:"2 Pinnwand-Downloads / Monat",feat_hd:"HD-Qualität",feat_photos:"Fotos & Videos",feat_pins:"<b>Unbegrenzt</b> Pins & Pinnwände",feat_profile:"Ganzes Profil & Bereiche",feat_zip:"ZIP, Ordner & PDF",feat_video:"Video (MP4) & Download-Warteschlange",btn_free:"Zu Chrome hinzufügen",btn_24h:"Tagespass holen",btn_2w:"2 Wochen holen",btn_1m:"1 Monat holen",btn_1y:"1 Jahr holen",foot_note:"Der 24-Stunden-Pass ist ein <b>einmaliger</b> Kauf (keine Verlängerung). 2-Wochen-/Monats-/Jahrespläne verlängern sich automatisch — <b>jederzeit kündbar</b>. Preise in USD."},
      es:{nav_how:"Cómo funciona",nav_features:"Funciones",nav_videos:"Vídeos",nav_pricing:"Precios",nav_faq:"Preguntas",nav_add:"Añadir a Chrome",hero_eyebrow:"Extensión de Chrome · 100% en tu navegador",hero_h1:"Guarda tableros de Pinterest <span class='red'>rápido</span>.",hero_lead:"Marca los pines que quieras directamente en la página y descárgalos en ZIP, carpeta o PDF. Sin pegar enlaces. Sin subidas. Sin esperas.",hero_cta1:"Añadir a Chrome — gratis",hero_cta2:"▶ Ver demo de 30 s",trust1:"Imágenes y vídeo en <b>HD</b>",trust2:"<b>Tableros privados</b> compatibles",trust3:"<b>Sin cuenta</b>, sin servidores",strip1_t:"Rápido",strip1_s:"Tablero entero en un clic",strip2_t:"Fácil",strip2_s:"Elige pines en la página",strip3_t:"Privado",strip3_s:"Funciona local, sin subidas",strip4_t:"Empieza gratis",strip4_s:"Se instala en segundos",price_eyebrow:"Precios",price_h2:"Elige cuánto tiempo lo necesitas.",price_lead:"Empieza gratis. Desbloquea <b>todo</b> desde $3.99 — sin bloqueos en los planes de pago.",plan_free:"Gratis",plan_24h:"24 horas",plan_2w:"2 semanas",plan_1m:"1 mes",plan_1y:"1 año",tag_onetime:"Pago único",tag_popular:"Popular",tag_best:"Mejor valor",per_free:"Sin tarjeta · empieza ya",per_24h:"Sin suscripción · el temporizador empieza al comprar",per_2w:"Se renueva cada 2 semanas · cancela cuando quieras",per_1m:"Pago mensual · cancela cuando quieras",per_1y:"≈ $6.58 / mes · pago anual · ahorra ~34%",free_saves:"20 pines guardados / mes",free_boards:"2 descargas de tableros / mes",feat_hd:"Calidad HD",feat_photos:"Fotos y vídeos",feat_pins:"Pines y tableros <b>ilimitados</b>",feat_profile:"Perfil y secciones completos",feat_zip:"ZIP, carpetas y PDF",feat_video:"Vídeo (MP4) y cola de descargas",btn_free:"Añadir a Chrome",btn_24h:"Pase de día",btn_2w:"2 semanas",btn_1m:"1 mes",btn_1y:"1 año",foot_note:"El pase de 24 horas es un pago <b>único</b> (sin renovación). Los planes de 2 semanas / mensual / anual se renuevan automáticamente — <b>cancela cuando quieras</b>. Precios en USD."},
      fr:{nav_how:"Comment ça marche",nav_features:"Fonctions",nav_videos:"Vidéos",nav_pricing:"Tarifs",nav_faq:"FAQ",nav_add:"Ajouter à Chrome",hero_eyebrow:"Extension Chrome · 100% dans votre navigateur",hero_h1:"Enregistrez vos tableaux Pinterest <span class='red'>en un éclair</span>.",hero_lead:"Cochez les épingles voulues directement sur la page et téléchargez-les en ZIP, dossier ou PDF. Sans coller de lien. Sans téléversement. Sans attente.",hero_cta1:"Ajouter à Chrome — gratuit",hero_cta2:"▶ Voir la démo de 30 s",trust1:"Images et vidéos <b>HD</b>",trust2:"<b>Tableaux privés</b> pris en charge",trust3:"<b>Sans compte</b>, sans serveur",strip1_t:"Rapide",strip1_s:"Tout le tableau en un clic",strip2_t:"Simple",strip2_s:"Choisissez les épingles sur la page",strip3_t:"Privé",strip3_s:"Tourne en local, sans envoi",strip4_t:"Gratuit au départ",strip4_s:"Installé en quelques secondes",price_eyebrow:"Tarifs",price_h2:"Choisissez la durée qu'il vous faut.",price_lead:"Commencez gratuitement. Débloquez <b>tout</b> dès $3.99 — aucune fonction bloquée sur les offres payantes.",plan_free:"Gratuit",plan_24h:"24 heures",plan_2w:"2 semaines",plan_1m:"1 mois",plan_1y:"1 an",tag_onetime:"Paiement unique",tag_popular:"Populaire",tag_best:"Meilleur prix",per_free:"Sans carte · démarrage immédiat",per_24h:"Sans abonnement · minuteur dès l'achat",per_2w:"Renouvelé toutes les 2 semaines · annulable à tout moment",per_1m:"Facturation mensuelle · annulable à tout moment",per_1y:"≈ $6.58 / mois · facturé à l'année · ~34% d'économie",free_saves:"20 épingles enregistrées / mois",free_boards:"2 téléchargements de tableaux / mois",feat_hd:"Qualité HD",feat_photos:"Photos et vidéos",feat_pins:"Épingles et tableaux <b>illimités</b>",feat_profile:"Profil et sections entiers",feat_zip:"ZIP, dossiers et PDF",feat_video:"Vidéo (MP4) et file de téléchargement",btn_free:"Ajouter à Chrome",btn_24h:"Pass journée",btn_2w:"2 semaines",btn_1m:"1 mois",btn_1y:"1 an",foot_note:"Le pass 24 h est un achat <b>unique</b> (sans renouvellement). Les offres 2 semaines / mensuelle / annuelle se renouvellent automatiquement — <b>annulable à tout moment</b>. Prix en USD."},
      hi:{nav_how:"यह कैसे काम करता है",nav_features:"विशेषताएँ",nav_videos:"वीडियो",nav_pricing:"कीमत",nav_faq:"सवाल-जवाब",nav_add:"Chrome में जोड़ें",hero_eyebrow:"Chrome एक्सटेंशन · 100% आपके ब्राउज़र में",hero_h1:"Pinterest बोर्ड <span class='red'>तेज़ी से</span> सेव करें।",hero_lead:"पेज पर ही मनचाहे पिन चुनें और उन्हें ZIP, फ़ोल्डर या PDF में डाउनलोड करें। न लिंक चिपकाना, न अपलोड, न इंतज़ार।",hero_cta1:"Chrome में जोड़ें — मुफ़्त",hero_cta2:"▶ 30-सेकंड डेमो देखें",trust1:"<b>HD</b> इमेज और वीडियो",trust2:"<b>निजी बोर्ड</b> समर्थित",trust3:"<b>कोई अकाउंट नहीं</b>, कोई सर्वर नहीं",strip1_t:"तेज़",strip1_s:"पूरा बोर्ड एक क्लिक में",strip2_t:"आसान",strip2_s:"पेज पर पिन चुनें",strip3_t:"निजी",strip3_s:"लोकल चलता है, कोई अपलोड नहीं",strip4_t:"मुफ़्त शुरुआत",strip4_s:"सेकंडों में इंस्टॉल",price_eyebrow:"कीमत",price_h2:"चुनें कि आपको कितने समय चाहिए।",price_lead:"मुफ़्त शुरू करें। $3.99 से <b>सब कुछ</b> अनलॉक करें — पेड प्लान में कोई रोक नहीं।",plan_free:"मुफ़्त",plan_24h:"24 घंटे",plan_2w:"2 हफ़्ते",plan_1m:"1 महीना",plan_1y:"1 साल",tag_onetime:"एकमुश्त",tag_popular:"लोकप्रिय",tag_best:"सबसे किफ़ायती",per_free:"कार्ड नहीं · तुरंत शुरू",per_24h:"कोई सब्सक्रिप्शन नहीं · खरीद से टाइमर शुरू",per_2w:"हर 2 हफ़्ते में नवीनीकरण · कभी भी रद्द करें",per_1m:"मासिक भुगतान · कभी भी रद्द करें",per_1y:"≈ $6.58 / माह · सालाना · ~34% बचत",free_saves:"20 पिन सेव / माह",free_boards:"2 बोर्ड डाउनलोड / माह",feat_hd:"HD क्वालिटी",feat_photos:"फ़ोटो और वीडियो",feat_pins:"<b>असीमित</b> पिन और बोर्ड",feat_profile:"पूरी प्रोफ़ाइल और सेक्शन",feat_zip:"ZIP, फ़ोल्डर और PDF",feat_video:"वीडियो (MP4) और डाउनलोड कतार",btn_free:"Chrome में जोड़ें",btn_24h:"डे पास लें",btn_2w:"2 हफ़्ते लें",btn_1m:"1 महीना लें",btn_1y:"1 साल लें",foot_note:"24-घंटे का पास <b>एकमुश्त</b> खरीद है (कोई नवीनीकरण नहीं)। 2 हफ़्ते / मासिक / सालाना प्लान अपने-आप नवीनीकृत होते हैं — <b>कभी भी रद्द करें</b>। कीमतें USD में।"},
      pt:{nav_how:"Como funciona",nav_features:"Recursos",nav_videos:"Vídeos",nav_pricing:"Preços",nav_faq:"Perguntas",nav_add:"Adicionar ao Chrome",hero_eyebrow:"Extensão do Chrome · 100% no seu navegador",hero_h1:"Salve pastas do Pinterest <span class='red'>rapidinho</span>.",hero_lead:"Marque os pins que quiser direto na página e baixe em ZIP, pasta ou PDF. Sem colar links. Sem uploads. Sem espera.",hero_cta1:"Adicionar ao Chrome — grátis",hero_cta2:"▶ Ver demo de 30 s",trust1:"Imagens e vídeo em <b>HD</b>",trust2:"<b>Pastas privadas</b> suportadas",trust3:"<b>Sem conta</b>, sem servidores",strip1_t:"Rápido",strip1_s:"Pasta inteira num clique",strip2_t:"Fácil",strip2_s:"Escolha pins na página",strip3_t:"Privado",strip3_s:"Roda local, sem uploads",strip4_t:"Comece grátis",strip4_s:"Instala em segundos",price_eyebrow:"Preços",price_h2:"Escolha por quanto tempo precisa.",price_lead:"Comece grátis. Libere <b>tudo</b> a partir de $3.99 — sem travas nos planos pagos.",plan_free:"Grátis",plan_24h:"24 horas",plan_2w:"2 semanas",plan_1m:"1 mês",plan_1y:"1 ano",tag_onetime:"Pagamento único",tag_popular:"Popular",tag_best:"Melhor custo",per_free:"Sem cartão · comece já",per_24h:"Sem assinatura · cronômetro começa na compra",per_2w:"Renova a cada 2 semanas · cancele quando quiser",per_1m:"Cobrança mensal · cancele quando quiser",per_1y:"≈ $6.58 / mês · cobrado por ano · economize ~34%",free_saves:"20 pins salvos / mês",free_boards:"2 downloads de pastas / mês",feat_hd:"Qualidade HD",feat_photos:"Fotos e vídeos",feat_pins:"Pins e pastas <b>ilimitados</b>",feat_profile:"Perfil e seções inteiros",feat_zip:"ZIP, pastas e PDF",feat_video:"Vídeo (MP4) e fila de downloads",btn_free:"Adicionar ao Chrome",btn_24h:"Passe de 1 dia",btn_2w:"2 semanas",btn_1m:"1 mês",btn_1y:"1 ano",foot_note:"O passe de 24 horas é uma compra <b>única</b> (sem renovação). Os planos de 2 semanas / mensal / anual renovam automaticamente — <b>cancele quando quiser</b>. Preços em USD."},
      ja:{nav_how:"使い方",nav_features:"機能",nav_videos:"動画",nav_pricing:"料金",nav_faq:"よくある質問",nav_add:"Chromeに追加",hero_eyebrow:"Chrome拡張機能 · 100%ブラウザ内で動作",hero_h1:"Pinterestのボードを<span class='red'>すばやく</span>保存。",hero_lead:"ページ上で欲しいピンにチェックを入れ、ZIP・フォルダ・PDFでダウンロード。リンクの貼り付けも、アップロードも、待ち時間も不要。",hero_cta1:"Chromeに追加 — 無料",hero_cta2:"▶ 30秒デモを見る",trust1:"<b>HD</b>画像・動画",trust2:"<b>非公開ボード</b>に対応",trust3:"<b>アカウント不要</b>・サーバー不要",strip1_t:"高速",strip1_s:"ボード全体をワンクリック",strip2_t:"簡単",strip2_s:"ページ上でピンを選択",strip3_t:"安全",strip3_s:"ローカル動作・アップロードなし",strip4_t:"無料で開始",strip4_s:"数秒でインストール",price_eyebrow:"料金",price_h2:"必要な期間を選ぶだけ。",price_lead:"無料で開始。$3.99から<b>すべて</b>解放 — 有料プランに機能制限なし。",plan_free:"無料",plan_24h:"24時間",plan_2w:"2週間",plan_1m:"1か月",plan_1y:"1年",tag_onetime:"買い切り",tag_popular:"人気",tag_best:"お得",per_free:"カード不要 · すぐ開始",per_24h:"サブスクなし · 購入時にタイマー開始",per_2w:"2週間ごとに更新 · いつでも解約可",per_1m:"毎月課金 · いつでも解約可",per_1y:"≈ $6.58 / 月 · 年額 · 約34%お得",free_saves:"ピン保存 月20件",free_boards:"ボードDL 月2回",feat_hd:"HD画質",feat_photos:"写真・動画",feat_pins:"ピン・ボード<b>無制限</b>",feat_profile:"プロフィール全体・セクション",feat_zip:"ZIP・フォルダ・PDF",feat_video:"動画(MP4)・ダウンロード待機列",btn_free:"Chromeに追加",btn_24h:"1日パス",btn_2w:"2週間",btn_1m:"1か月",btn_1y:"1年",foot_note:"24時間パスは<b>買い切り</b>（更新なし）。2週間／月額／年額プランは自動更新 — <b>いつでも解約可</b>。価格はUSD。"},
      it:{nav_how:"Come funziona",nav_features:"Funzioni",nav_videos:"Video",nav_pricing:"Prezzi",nav_faq:"FAQ",nav_add:"Aggiungi a Chrome",hero_eyebrow:"Estensione Chrome · 100% nel tuo browser",hero_h1:"Salva le bacheche Pinterest <span class='red'>in un lampo</span>.",hero_lead:"Seleziona i pin che vuoi direttamente sulla pagina e scaricali in ZIP, cartella o PDF. Niente link da incollare. Niente upload. Nessuna attesa.",hero_cta1:"Aggiungi a Chrome — gratis",hero_cta2:"▶ Guarda la demo di 30 s",trust1:"Immagini e video in <b>HD</b>",trust2:"<b>Bacheche private</b> supportate",trust3:"<b>Nessun account</b>, nessun server",strip1_t:"Veloce",strip1_s:"Bacheca intera in un clic",strip2_t:"Facile",strip2_s:"Scegli i pin sulla pagina",strip3_t:"Privato",strip3_s:"Funziona in locale, senza upload",strip4_t:"Inizia gratis",strip4_s:"Installazione in pochi secondi",price_eyebrow:"Prezzi",price_h2:"Scegli per quanto ti serve.",price_lead:"Inizia gratis. Sblocca <b>tutto</b> da $3.99 — nessun blocco sui piani a pagamento.",plan_free:"Gratis",plan_24h:"24 ore",plan_2w:"2 settimane",plan_1m:"1 mese",plan_1y:"1 anno",tag_onetime:"Una tantum",tag_popular:"Popolare",tag_best:"Conveniente",per_free:"Senza carta · inizia subito",per_24h:"Nessun abbonamento · timer dall'acquisto",per_2w:"Si rinnova ogni 2 settimane · disdici quando vuoi",per_1m:"Addebito mensile · disdici quando vuoi",per_1y:"≈ $6.58 / mese · annuale · risparmi ~34%",free_saves:"20 pin salvati / mese",free_boards:"2 download di bacheche / mese",feat_hd:"Qualità HD",feat_photos:"Foto e video",feat_pins:"Pin e bacheche <b>illimitati</b>",feat_profile:"Profilo e sezioni interi",feat_zip:"ZIP, cartelle e PDF",feat_video:"Video (MP4) e coda di download",btn_free:"Aggiungi a Chrome",btn_24h:"Pass giornaliero",btn_2w:"2 settimane",btn_1m:"1 mese",btn_1y:"1 anno",foot_note:"Il pass di 24 ore è un acquisto <b>una tantum</b> (senza rinnovo). I piani 2 settimane / mensile / annuale si rinnovano automaticamente — <b>disdici quando vuoi</b>. Prezzi in USD."},
      pl:{nav_how:"Jak to działa",nav_features:"Funkcje",nav_videos:"Wideo",nav_pricing:"Cennik",nav_faq:"FAQ",nav_add:"Dodaj do Chrome",hero_eyebrow:"Rozszerzenie Chrome · 100% w Twojej przeglądarce",hero_h1:"Zapisuj tablice Pinterest <span class='red'>błyskawicznie</span>.",hero_lead:"Zaznacz wybrane piny bezpośrednio na stronie i pobierz je jako ZIP, folder lub PDF. Bez wklejania linków. Bez przesyłania. Bez czekania.",hero_cta1:"Dodaj do Chrome — za darmo",hero_cta2:"▶ Zobacz demo 30 s",trust1:"Zdjęcia i wideo w <b>HD</b>",trust2:"<b>Prywatne tablice</b> obsługiwane",trust3:"<b>Bez konta</b>, bez serwerów",strip1_t:"Szybko",strip1_s:"Cała tablica jednym kliknięciem",strip2_t:"Łatwo",strip2_s:"Wybierz piny na stronie",strip3_t:"Prywatnie",strip3_s:"Działa lokalnie, bez wysyłania",strip4_t:"Zacznij za darmo",strip4_s:"Instalacja w kilka sekund",price_eyebrow:"Cennik",price_h2:"Wybierz, na jak długo go potrzebujesz.",price_lead:"Zacznij za darmo. Odblokuj <b>wszystko</b> od $3.99 — żadnych blokad w planach płatnych.",plan_free:"Za darmo",plan_24h:"24 godziny",plan_2w:"2 tygodnie",plan_1m:"1 miesiąc",plan_1y:"1 rok",tag_onetime:"Jednorazowo",tag_popular:"Popularne",tag_best:"Najlepsza cena",per_free:"Bez karty · zacznij od razu",per_24h:"Bez subskrypcji · licznik od zakupu",per_2w:"Odnawia się co 2 tygodnie · anuluj w każdej chwili",per_1m:"Płatność miesięczna · anuluj w każdej chwili",per_1y:"≈ $6.58 / mies · rocznie · oszczędzasz ~34%",free_saves:"20 zapisów pinów / miesiąc",free_boards:"2 pobrania tablic / miesiąc",feat_hd:"Jakość HD",feat_photos:"Zdjęcia i wideo",feat_pins:"<b>Bez limitu</b> pinów i tablic",feat_profile:"Cały profil i sekcje",feat_zip:"ZIP, foldery i PDF",feat_video:"Wideo (MP4) i kolejka pobierania",btn_free:"Dodaj do Chrome",btn_24h:"Bilet dzienny",btn_2w:"2 tygodnie",btn_1m:"1 miesiąc",btn_1y:"1 rok",foot_note:"Bilet 24-godzinny to zakup <b>jednorazowy</b> (bez odnawiania). Plany 2-tygodniowy / miesięczny / roczny odnawiają się automatycznie — <b>anuluj w każdej chwili</b>. Ceny w USD."},
      tr:{nav_how:"Nasıl çalışır",nav_features:"Özellikler",nav_videos:"Videolar",nav_pricing:"Fiyatlar",nav_faq:"SSS",nav_add:"Chrome'a ekle",hero_eyebrow:"Chrome uzantısı · %100 tarayıcında",hero_h1:"Pinterest panolarını <span class='red'>hızlıca</span> kaydet.",hero_lead:"İstediğin pinleri sayfanın üzerinde işaretle ve ZIP, klasör ya da PDF olarak indir. Bağlantı yapıştırmak yok. Yükleme yok. Bekleme yok.",hero_cta1:"Chrome'a ekle — ücretsiz",hero_cta2:"▶ 30 sn demoyu izle",trust1:"<b>HD</b> görsel ve video",trust2:"<b>Gizli panolar</b> destekli",trust3:"<b>Hesap yok</b>, sunucu yok",strip1_t:"Hızlı",strip1_s:"Tüm pano tek tıkla",strip2_t:"Kolay",strip2_s:"Pinleri sayfada seç",strip3_t:"Gizli",strip3_s:"Yerelde çalışır, yükleme yok",strip4_t:"Ücretsiz başla",strip4_s:"Saniyeler içinde kurulur",price_eyebrow:"Fiyatlar",price_h2:"Ne kadar süre lazımsa onu seç.",price_lead:"Ücretsiz başla. $3.99'dan itibaren <b>her şeyi</b> aç — ücretli planlarda kilit yok.",plan_free:"Ücretsiz",plan_24h:"24 saat",plan_2w:"2 hafta",plan_1m:"1 ay",plan_1y:"1 yıl",tag_onetime:"Tek seferlik",tag_popular:"Popüler",tag_best:"En avantajlı",per_free:"Kart yok · hemen başla",per_24h:"Abonelik yok · sayaç satın alımda başlar",per_2w:"2 haftada bir yenilenir · istediğin zaman iptal et",per_1m:"Aylık ödeme · istediğin zaman iptal et",per_1y:"≈ $6.58 / ay · yıllık · ~%34 tasarruf",free_saves:"Aylık 20 pin kaydı",free_boards:"Aylık 2 pano indirme",feat_hd:"HD kalite",feat_photos:"Fotoğraf ve video",feat_pins:"<b>Sınırsız</b> pin ve pano",feat_profile:"Tüm profil ve bölümler",feat_zip:"ZIP, klasör ve PDF",feat_video:"Video (MP4) ve indirme kuyruğu",btn_free:"Chrome'a ekle",btn_24h:"Günlük geçiş",btn_2w:"2 hafta al",btn_1m:"1 ay al",btn_1y:"1 yıl al",foot_note:"24 saatlik geçiş <b>tek seferlik</b> bir satın almadır (yenileme yok). 2 hafta / aylık / yıllık planlar otomatik yenilenir — <b>istediğin zaman iptal et</b>. Fiyatlar USD."},
      ko:{nav_how:"사용 방법",nav_features:"기능",nav_videos:"동영상",nav_pricing:"요금",nav_faq:"FAQ",nav_add:"Chrome에 추가",hero_eyebrow:"Chrome 확장 프로그램 · 100% 브라우저에서 실행",hero_h1:"Pinterest 보드를 <span class='red'>빠르게</span> 저장하세요.",hero_lead:"원하는 핀을 페이지에서 바로 체크하고 ZIP, 폴더, PDF로 다운로드하세요. 링크 붙여넣기 없음. 업로드 없음. 기다림 없음.",hero_cta1:"Chrome에 추가 — 무료",hero_cta2:"▶ 30초 데모 보기",trust1:"<b>HD</b> 이미지 및 동영상",trust2:"<b>비공개 보드</b> 지원",trust3:"<b>계정 불필요</b>, 서버 없음",strip1_t:"빠름",strip1_s:"보드 전체를 한 번에",strip2_t:"쉬움",strip2_s:"페이지에서 핀 선택",strip3_t:"비공개",strip3_s:"로컬 실행, 업로드 없음",strip4_t:"무료 시작",strip4_s:"몇 초 만에 설치",price_eyebrow:"요금",price_h2:"필요한 기간을 선택하세요.",price_lead:"무료로 시작하세요. $3.99부터 <b>모든 기능</b> 잠금 해제 — 유료 플랜에 제한 없음.",plan_free:"무료",plan_24h:"24시간",plan_2w:"2주",plan_1m:"1개월",plan_1y:"1년",tag_onetime:"1회 결제",tag_popular:"인기",tag_best:"가성비",per_free:"카드 불필요 · 즉시 시작",per_24h:"구독 없음 · 구매 시 타이머 시작",per_2w:"2주마다 갱신 · 언제든 취소",per_1m:"매월 결제 · 언제든 취소",per_1y:"≈ $6.58 / 월 · 연간 결제 · 약 34% 절약",free_saves:"월 20개 핀 저장",free_boards:"월 2회 보드 다운로드",feat_hd:"HD 화질",feat_photos:"사진 및 동영상",feat_pins:"<b>무제한</b> 핀과 보드",feat_profile:"전체 프로필 및 섹션",feat_zip:"ZIP, 폴더, PDF",feat_video:"동영상(MP4) 및 다운로드 대기열",btn_free:"Chrome에 추가",btn_24h:"1일 이용권",btn_2w:"2주 구매",btn_1m:"1개월 구매",btn_1y:"1년 구매",foot_note:"24시간 이용권은 <b>1회성</b> 구매입니다(갱신 없음). 2주 / 월간 / 연간 플랜은 자동 갱신되며 — <b>언제든 취소</b>할 수 있습니다. 가격은 USD."},
      nl:{nav_how:"Hoe het werkt",nav_features:"Functies",nav_videos:"Video's",nav_pricing:"Prijzen",nav_faq:"FAQ",nav_add:"Toevoegen aan Chrome",hero_eyebrow:"Chrome-extensie · 100% in je browser",hero_h1:"Pinterest-borden <span class='red'>razendsnel</span> opslaan.",hero_lead:"Vink de gewenste pins direct op de pagina aan en download ze als ZIP, map of PDF. Geen links plakken. Geen uploads. Geen wachten.",hero_cta1:"Toevoegen aan Chrome — gratis",hero_cta2:"▶ Bekijk demo van 30 s",trust1:"<b>HD</b> afbeeldingen & video",trust2:"<b>Privéborden</b> ondersteund",trust3:"<b>Geen account</b>, geen servers",strip1_t:"Snel",strip1_s:"Heel bord met één klik",strip2_t:"Makkelijk",strip2_s:"Kies pins op de pagina",strip3_t:"Privé",strip3_s:"Draait lokaal, geen uploads",strip4_t:"Gratis starten",strip4_s:"In seconden geïnstalleerd",price_eyebrow:"Prijzen",price_h2:"Kies hoe lang je het nodig hebt.",price_lead:"Begin gratis. Ontgrendel <b>alles</b> vanaf $3.99 — geen functieblokkades op betaalde plannen.",plan_free:"Gratis",plan_24h:"24 uur",plan_2w:"2 weken",plan_1m:"1 maand",plan_1y:"1 jaar",tag_onetime:"Eenmalig",tag_popular:"Populair",tag_best:"Beste deal",per_free:"Geen kaart · meteen starten",per_24h:"Geen abonnement · timer start bij aankoop",per_2w:"Verlengt elke 2 weken · altijd opzegbaar",per_1m:"Maandelijkse facturering · altijd opzegbaar",per_1y:"≈ $6.58 / mnd · jaarlijks · ~34% korting",free_saves:"20 pins opslaan / maand",free_boards:"2 borddownloads / maand",feat_hd:"HD-kwaliteit",feat_photos:"Foto's & video's",feat_pins:"<b>Onbeperkt</b> pins & borden",feat_profile:"Volledig profiel & secties",feat_zip:"ZIP, mappen & PDF",feat_video:"Video (MP4) & downloadwachtrij",btn_free:"Toevoegen aan Chrome",btn_24h:"Dagpas",btn_2w:"2 weken",btn_1m:"1 maand",btn_1y:"1 jaar",foot_note:"De pas van 24 uur is een <b>eenmalige</b> aankoop (geen verlenging). Plannen van 2 weken / maand / jaar verlengen automatisch — <b>altijd opzegbaar</b>. Prijzen in USD."},
      zh:{nav_how:"使用方法",nav_features:"功能",nav_videos:"视频",nav_pricing:"价格",nav_faq:"常见问题",nav_add:"添加到 Chrome",hero_eyebrow:"Chrome 扩展 · 100% 在你的浏览器中运行",hero_h1:"<span class='red'>极速</span>保存 Pinterest 画板。",hero_lead:"在页面上直接勾选想要的图钉，下载为 ZIP、文件夹或 PDF。无需粘贴链接，无需上传，无需等待。",hero_cta1:"添加到 Chrome — 免费",hero_cta2:"▶ 观看 30 秒演示",trust1:"<b>高清</b>图片和视频",trust2:"支持<b>私密画板</b>",trust3:"<b>无需账号</b>，无服务器",strip1_t:"快速",strip1_s:"整个画板一键搞定",strip2_t:"简单",strip2_s:"在页面上选择图钉",strip3_t:"私密",strip3_s:"本地运行，不上传",strip4_t:"免费开始",strip4_s:"几秒即可安装",price_eyebrow:"价格",price_h2:"选择你需要的时长。",price_lead:"免费开始。$3.99 起<b>解锁全部</b>——付费方案无任何功能限制。",plan_free:"免费",plan_24h:"24 小时",plan_2w:"2 周",plan_1m:"1 个月",plan_1y:"1 年",tag_onetime:"一次性",tag_popular:"热门",tag_best:"超值",per_free:"无需银行卡 · 立即开始",per_24h:"无订阅 · 购买即开始计时",per_2w:"每 2 周续费 · 随时取消",per_1m:"按月计费 · 随时取消",per_1y:"≈ $6.58 / 月 · 按年计费 · 省约 34%",free_saves:"每月保存 20 个图钉",free_boards:"每月下载 2 个画板",feat_hd:"高清画质",feat_photos:"图片和视频",feat_pins:"<b>无限</b>图钉和画板",feat_profile:"完整主页和分区",feat_zip:"ZIP、文件夹和 PDF",feat_video:"视频 (MP4) 和下载队列",btn_free:"添加到 Chrome",btn_24h:"购买日通",btn_2w:"购买 2 周",btn_1m:"购买 1 个月",btn_1y:"购买 1 年",foot_note:"24 小时通行证为<b>一次性</b>购买（不续费）。2 周 / 月 / 年方案自动续费——<b>随时取消</b>。价格以美元计。"},
      ar:{nav_how:"كيف يعمل",nav_features:"الميزات",nav_videos:"فيديوهات",nav_pricing:"الأسعار",nav_faq:"الأسئلة الشائعة",nav_add:"أضِف إلى Chrome",hero_eyebrow:"إضافة Chrome · 100% داخل متصفحك",hero_h1:"احفظ لوحات Pinterest <span class='red'>بسرعة</span>.",hero_lead:"حدِّد الدبابيس التي تريدها مباشرةً على الصفحة ونزِّلها كملف ZIP أو مجلد أو PDF. بلا لصق روابط. بلا رفع. بلا انتظار.",hero_cta1:"أضِف إلى Chrome — مجانًا",hero_cta2:"▶ شاهد عرضًا في 30 ثانية",trust1:"صور وفيديو بدقة <b>HD</b>",trust2:"دعم <b>اللوحات الخاصة</b>",trust3:"<b>بدون حساب</b> وبدون خوادم",strip1_t:"سريع",strip1_s:"لوحة كاملة بنقرة واحدة",strip2_t:"سهل",strip2_s:"اختر الدبابيس على الصفحة",strip3_t:"خاص",strip3_s:"يعمل محليًا بلا رفع",strip4_t:"ابدأ مجانًا",strip4_s:"يُثبَّت في ثوانٍ",price_eyebrow:"الأسعار",price_h2:"اختر المدة التي تحتاجها.",price_lead:"ابدأ مجانًا. افتح <b>كل المزايا</b> ابتداءً من $3.99 — بلا قيود في الباقات المدفوعة.",plan_free:"مجاني",plan_24h:"24 ساعة",plan_2w:"أسبوعان",plan_1m:"شهر",plan_1y:"سنة",tag_onetime:"دفعة واحدة",tag_popular:"الأكثر رواجًا",tag_best:"الأفضل قيمةً",per_free:"بدون بطاقة · ابدأ فورًا",per_24h:"بلا اشتراك · يبدأ المؤقّت عند الشراء",per_2w:"يتجدد كل أسبوعين · ألغِ في أي وقت",per_1m:"فوترة شهرية · ألغِ في أي وقت",per_1y:"≈ $6.58 / شهر · فوترة سنوية · وفّر ~34%",free_saves:"20 حفظ دبوس / شهر",free_boards:"تنزيل لوحتين / شهر",feat_hd:"جودة HD",feat_photos:"صور وفيديو",feat_pins:"دبابيس ولوحات <b>غير محدودة</b>",feat_profile:"الملف الشخصي والأقسام كاملةً",feat_zip:"ZIP ومجلدات وPDF",feat_video:"فيديو (MP4) وقائمة انتظار التنزيل",btn_free:"أضِف إلى Chrome",btn_24h:"تذكرة يوم",btn_2w:"أسبوعان",btn_1m:"شهر",btn_1y:"سنة",foot_note:"تذكرة الـ24 ساعة عملية شراء <b>لمرة واحدة</b> (بلا تجديد). باقات الأسبوعين / الشهر / السنة تتجدد تلقائيًا — <b>ألغِ في أي وقت</b>. الأسعار بالدولار الأمريكي."}
    }

    // short-pass intro line (added per language)
    var SPASS = {ru:"Нужно ненадолго?",de:"Nur kurz nötig?",es:"¿Solo por poco tiempo?",fr:"Besoin juste pour un moment ?",hi:"बस थोड़े समय के लिए चाहिए?",pt:"Precisa só por pouco tempo?",ja:"ちょっとだけ使いたい？",it:"Ti serve solo per poco?",pl:"Potrzebujesz na krótko?",tr:"Sadece kısa süre mi lazım?",ko:"잠깐만 필요하세요?",nl:"Heb je het maar kort nodig?",zh:"只需要短期使用？",ar:"تحتاجه لفترة قصيرة فقط؟"}
    Object.keys(SPASS).forEach(function (l) { if (T[l]) T[l].spass_lead = SPASS[l] })

    var root = document.documentElement
    var nodes = [].slice.call(document.querySelectorAll('[data-i18n]'))
    var EN = {} // snapshot the English source from the markup (fallback + restore)
    nodes.forEach(function (el) { EN[el.getAttribute('data-i18n')] = el.innerHTML })

    function apply(lang) {
      var dict = T[lang] || {}
      nodes.forEach(function (el) {
        var k = el.getAttribute('data-i18n')
        el.innerHTML = (lang !== 'en' && dict[k] != null) ? dict[k] : EN[k]
      })
      root.setAttribute('lang', lang)
      root.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr')
      var meta = LANGS.filter(function (l) { return l[0] === lang })[0] || LANGS[0]
      document.getElementById('langFlag').textContent = meta[1]
      document.getElementById('langCode').textContent = lang.toUpperCase()
      var m = document.getElementById('langMenu')
      Array.prototype.slice.call(m.children).forEach(function (b) { b.classList.toggle('on', b.dataset.l === lang) })
    }

    // build the menu
    var menu = document.getElementById('langMenu')
    LANGS.forEach(function (l) {
      var b = document.createElement('button')
      b.type = 'button'
      b.dataset.l = l[0]
      b.innerHTML = '<span class="fl">' + l[1] + '</span>' + l[2] + '<span class="ck">✓</span>'
      b.addEventListener('click', function () {
        localStorage.setItem('pg-lang', l[0])
        apply(l[0])
        menu.hidden = true
      })
      menu.appendChild(b)
    })

    var btn = document.getElementById('langBtn')
    btn.addEventListener('click', function (e) { e.stopPropagation(); menu.hidden = !menu.hidden })
    document.addEventListener('click', function () { menu.hidden = true })
    menu.addEventListener('click', function (e) { e.stopPropagation() })

    // English is the primary/default language: always start in English unless the user explicitly
    // picked another (remembered). No browser auto-detect — English first, every time.
    var saved = localStorage.getItem('pg-lang')
    apply(saved || 'en')
  })()
